import type { Metadata } from "next";
import "../globals.css";
import { Toaster } from "@/components/ui/sonner";


export const metadata: Metadata = {
    title: "Authentication",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html>
            <body>
                <div>
                    <Toaster position="top-center" richColors />
                    {children}
                </div>
            </body>
        </html>

    );
}
