import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";
import { ProgressBar } from "@/components/shared/ProgressLink";
import Script from "next/script";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Bakery Bazzar",
    description: "Generated by create next app",
};

import QueryProvider from "@/providers/query-provider";
import { ThemeProvider } from "@/components/dashboard-stuffs/theme-provider";

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" suppressHydrationWarning>
            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased`}
            >
                <Script src="https://checkout.razorpay.com/v1/checkout.js" strategy="lazyOnload" />
                <QueryProvider>
                    <ThemeProvider
                        attribute="class"
                        defaultTheme="system"
                        enableSystem
                        disableTransitionOnChange
                    >
                        <ProgressBar className="bg-primary/60 h-1">
                            <Toaster position="top-center" richColors />

                            {children}
                        </ProgressBar>
                    </ThemeProvider>
                </QueryProvider>
            </body>
        </html>
    );
}
