import type { Metadata } from "next";
import "@/app/globals.css";
import { Toaster } from "@/components/ui/sonner";
import { ThemeProvider } from "@/components/dashboard-stuffs/theme-provider";


export const metadata: Metadata = {
    title: "Shop-Authentication",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html suppressHydrationWarning>
            <body>
                <div>
                    <Toaster position="top-center" richColors />
                    <ThemeProvider
                        attribute="class"
                        defaultTheme="system"
                        enableSystem
                        disableTransitionOnChange>
                        {children}

                    </ThemeProvider>
                </div>
            </body>
        </html>

    );
}
